services:
  web:
    build: .
    image: stock_scanner_app:latest
    container_name: stock_scanner_web
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./conf:/app/conf
      - ./trade_log.json:/app/trade_log.json
      - ./alerted_today.json:/app/alerted_today.json
    command: gunicorn app:app --bind 0.0.0.0:5000 --timeout 600 --workers 2

  indicator_bot:
    image: stock_scanner_app:latest
    container_name: stock_scanner_bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./conf:/app/conf
      - ./trade_log.json:/app/trade_log.json
      - ./alerted_today.json:/app/alerted_today.json
    command: python indicator_bot.py
    depends_on:
      - web
